name: Update Commodity History Chart Data

on:
  schedule:
    - cron: "0 2 * * *"  # jam 09:00 WIB
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Yahoo Finance fetcher
        run: python get_commodity_history.py

      - name: Commit and push JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          if [ -f "commodity_history.json" ]; then
            git add commodity_history.json
            git commit -m "📈 Auto-update commodity history data" || echo "No changes to commit"
            git push || echo "Nothing to push"
          else
            echo "⚠️ File commodity_history.json not found — skipping commit."
          fi
